### ISSUE TITLE
Question: Are there plans for a build step for lambdas?

### ISSUE THREAD

**Issue by alexbepple** [arc-repos/arc.codes#80]
If I am not mistaken, the current deployment process uploads everything in the folder of a lambda. This includes all the cruft in `node_modules/*`.

Are there plans for having a build step for the lambdas?

Then we could bring down the sizes of the lambdas down massively, e.g. through tree-shaking.

**Comment by brianleroux** [comment]
yes there's a spot for it tho we haven't really found it necessary for our case (we keep things pretty tight) but that said there is this plugin too  https://github.com/arc-repos/arc-plugin-node-prune

another thing I've seen folks do is compiling code into the src folder using something like `ncc` and treading arc as a dumb deployment vehicle. lets leave this open tho because I think we should add this feature as a first class thing.

**Comment by alexbepple** [comment]
@brianleroux Plugins? 😲 Good to know. Thanks. They are not documented either, are they? 😉

**Comment by brianleroux** [comment]
No, they're not formalized yet really tho we appreciate all the help we can get!
